# frozen_string_literal: true
#
# Post-processes a Ruby parser generated by Ragel, moving its integer table
# literals into a packed binary data file next to it (foo_parser.rb gets
# foo_parser.dat). The parser reads that file once at load time and unpacks
# each table into the same Array with Mail::ParserTools#unpack_table.
#
# Ruby has to compile every element of a large Array literal, which costs far
# more memory (AST nodes, instruction sequences, heap fragmentation) than the
# table itself, and the literals made the generated parsers hard to read.
# Unpacking from a data file produces identical Arrays without that overhead,
# so the generated state machine code is unchanged.
#
# Usage: ruby tools/pack_ragel_tables.rb lib/mail/parsers/foo_parser.rb

TABLE = /^(?<indent>[ \t]*)self\.(?<name>\w+) = \[\n(?<body>[\d,\s]*?)\n\k<indent>\]\n/
EXTEND = /^(?<indent>[ \t]*)extend Mail::ParserTools\n/

def directive_for(values)
  raise ArgumentError, 'negative table value' if values.any?(&:negative?)

  max = values.max || 0
  if max <= 0xFF then 'C*'
  elsif max <= 0xFFFF then 'v*'
  elsif max <= 0xFFFF_FFFF then 'V*'
  else raise ArgumentError, "table value #{max} too large to pack"
  end
end

ARGV.each do |path|
  data_path = path.sub(/\.rb\z/, '.dat')
  raise ArgumentError, "#{path} is not a .rb file" if data_path == path

  source = File.read(path)
  data = String.new(encoding: Encoding::BINARY)
  packed = source.gsub(TABLE) do
    m = Regexp.last_match
    values = m[:body].scan(/\d+/).map(&:to_i)
    directive = directive_for(values)
    bytes = values.pack(directive)
    call = "unpack_table(tables, #{data.bytesize}, #{bytes.bytesize}, #{directive.dump})"
    data << bytes
    "#{m[:indent]}self.#{m[:name]} = #{call}\n"
  end
  next if data.empty?

  read = "tables = File.binread(File.join(__dir__, #{File.basename(data_path).dump}))"
  packed.sub!(EXTEND) { "#{$&}#{$~[:indent]}#{read}\n" } or
    raise ArgumentError, "#{path}: no `extend Mail::ParserTools` to read the tables after"

  File.binwrite(data_path, data)
  File.write(path, packed)
end
